from django.conf import settings

FINANCE_SERVICE_URL = settings.FINANCE_CATEGORY_URL
FINANCE_STOCK_PRICE_ENDPOINT = '/stock_price/'
FINANCE_CURRENCY_CONVERTER_ENDPOINT = '/currency_converter/'
FINANCE_GET_SPECIFIC_STOCK_PRICE = 'GET_SPECIFIC_STOCK_PRICE'
FINANCE_GET_GENERIC_STOCK_PRICE = 'GET_GENERIC_STOCK_PRICE'
FINANCE_CATEGORY = 'FINANCING'
