from django.conf import settings

MESSAGING_SERVICE_URL = settings.MESSAGING_CATEGORY_URL
MESSAGING_EMAIL_ENDPOINT = '/send_email/'
MESSAGING_DISCORD_ENDPOINT = '/send_discord_message/'
MESSAGING_PURPOSE_SEND_MAIL = 'SEND_EMAIL'
MESSAGING_CATEGORY = 'MESSAGING'
